//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronicObserver.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ElectronicObserver.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 をご利用いただきありがとうございます。\r\n設定や使用方法については「ヘルプ」→「オンラインヘルプ」を参照してください。\r\nご使用の前に必ずご一読ください。 的本地化字符串。
        /// </summary>
        internal static string Configuration_1 {
            get {
                return ResourceManager.GetString("Configuration_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初回起動メッセージ 的本地化字符串。
        /// </summary>
        internal static string Configuration_2 {
            get {
                return ResourceManager.GetString("Configuration_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Meiryo UI 的本地化字符串。
        /// </summary>
        internal static string Configuration_Font {
            get {
                return ResourceManager.GetString("Configuration_Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 装備可能艦種: 的本地化字符串。
        /// </summary>
        internal static string DialogAlbumMasterEquipment_1 {
            get {
                return ResourceManager.GetString("DialogAlbumMasterEquipment_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 装備図鑑 CSVの出力に失敗しました。\r\n 的本地化字符串。
        /// </summary>
        internal static string DialogAlbumMasterEquipment_10 {
            get {
                return ResourceManager.GetString("DialogAlbumMasterEquipment_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 エラー 的本地化字符串。
        /// </summary>
        internal static string DialogAlbumMasterEquipment_11 {
            get {
                return ResourceManager.GetString("DialogAlbumMasterEquipment_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 なし 的本地化字符串。
        /// </summary>
        internal static string DialogAlbumMasterEquipment_2 {
            get {
                return ResourceManager.GetString("DialogAlbumMasterEquipment_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 装備図鑑 -  的本地化字符串。
        /// </summary>
        internal static string DialogAlbumMasterEquipment_3 {
            get {
                return ResourceManager.GetString("DialogAlbumMasterEquipment_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 装備ID,図鑑番号,装備種,装備名,装備種1,装備種2,装備種3,装備種4,火力,雷装,対空,装甲,対潜,回避,索敵,運,命中,爆装,射程,レア,廃棄燃料,廃棄弾薬,廃棄鋼材,廃棄ボーキ,図鑑文章,バージョン 的本地化字符串。
        /// </summary>
        internal static string DialogAlbumMasterEquipment_4 {
            get {
                return ResourceManager.GetString("DialogAlbumMasterEquipment_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 装備図鑑 CSVの出力に失敗しました。 的本地化字符串。
        /// </summary>
        internal static string DialogAlbumMasterEquipment_5 {
            get {
                return ResourceManager.GetString("DialogAlbumMasterEquipment_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 装備図鑑 CSVの出力に失敗しました。\r\n 的本地化字符串。
        /// </summary>
        internal static string DialogAlbumMasterEquipment_6 {
            get {
                return ResourceManager.GetString("DialogAlbumMasterEquipment_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 エラー 的本地化字符串。
        /// </summary>
        internal static string DialogAlbumMasterEquipment_7 {
            get {
                return ResourceManager.GetString("DialogAlbumMasterEquipment_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 装備ID,図鑑番号,装備名,装備種1,装備種2,装備種3,装備種4,火力,雷装,対空,装甲,対潜,回避,索敵,運,命中,爆装,射程,レア,廃棄燃料,廃棄弾薬,廃棄鋼材,廃棄ボーキ,図鑑文章,バージョン 的本地化字符串。
        /// </summary>
        internal static string DialogAlbumMasterEquipment_8 {
            get {
                return ResourceManager.GetString("DialogAlbumMasterEquipment_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 装備図鑑 CSVの出力に失敗しました。 的本地化字符串。
        /// </summary>
        internal static string DialogAlbumMasterEquipment_9 {
            get {
                return ResourceManager.GetString("DialogAlbumMasterEquipment_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 陸上基地 的本地化字符串。
        /// </summary>
        internal static string DialogAlbumMasterShip_1 {
            get {
                return ResourceManager.GetString("DialogAlbumMasterShip_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 装甲 {0}{1}\r\n 的本地化字符串。
        /// </summary>
        internal static string DialogAlbumMasterShip_10 {
            get {
                return ResourceManager.GetString("DialogAlbumMasterShip_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 対潜 {0}{1}\r\n 的本地化字符串。
        /// </summary>
        internal static string DialogAlbumMasterShip_11 {
            get {
                return ResourceManager.GetString("DialogAlbumMasterShip_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回避 {0}{1}\r\n 的本地化字符串。
        /// </summary>
        internal static string DialogAlbumMasterShip_12 {
            get {
                return ResourceManager.GetString("DialogAlbumMasterShip_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 索敵 {0}{1}\r\n 的本地化字符串。
        /// </summary>
        internal static string DialogAlbumMasterShip_13 {
            get {
                return ResourceManager.GetString("DialogAlbumMasterShip_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 命中 {0}{1}\r\n 的本地化字符串。
        /// </summary>
        internal static string DialogAlbumMasterShip_14 {
            get {
                return ResourceManager.GetString("DialogAlbumMasterShip_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 爆装 {0}{1}\r\n 的本地化字符串。
        /// </summary>
        internal static string DialogAlbumMasterShip_15 {
            get {
                return ResourceManager.GetString("DialogAlbumMasterShip_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (右クリックで図鑑) 的本地化字符串。
        /// </summary>
        internal static string DialogAlbumMasterShip_16 {
            get {
                return ResourceManager.GetString("DialogAlbumMasterShip_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (なし) 的本地化字符串。
        /// </summary>
        internal static string DialogAlbumMasterShip_17 {
            get {
                return ResourceManager.GetString("DialogAlbumMasterShip_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 艦船図鑑 - 的本地化字符串。
        /// </summary>
        internal static string DialogAlbumMasterShip_18 {
            get {
                return ResourceManager.GetString("DialogAlbumMasterShip_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 艦船ID,図鑑番号,艦種,艦名,読み,改装前,改装後,改装Lv,改装弾薬,改装鋼材,改装設計図,耐久初期,耐久結婚,火力初期,火力最大,雷装初期,雷装最大,対空初期,対空最大,装甲初期,装甲最大,対潜初期,対潜最大,回避初期,回避最大,索敵初期,索敵最大,運初期,運最大,速力,射程,レア,スロット数,搭載機数1,搭載機数2,搭載機数3,搭載機数4,搭載機数5,初期装備1,初期装備2,初期装備3,初期装備4,初期装備5,建造時間,解体燃料,解体弾薬,解体鋼材,解体ボーキ,改修火力,改修雷装,改修対空,改修装甲,ドロップ文章,図鑑文章,搭載燃料,搭載弾薬,ボイス,リソース名,バージョン 的本地化字符串。
        /// </summary>
        internal static string DialogAlbumMasterShip_19 {
            get {
                return ResourceManager.GetString("DialogAlbumMasterShip_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初期値 的本地化字符串。
        /// </summary>
        internal static string DialogAlbumMasterShip_2 {
            get {
                return ResourceManager.GetString("DialogAlbumMasterShip_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 なし 的本地化字符串。
        /// </summary>
        internal static string DialogAlbumMasterShip_20 {
            get {
                return ResourceManager.GetString("DialogAlbumMasterShip_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 枚 的本地化字符串。
        /// </summary>
        internal static string DialogAlbumMasterShip_21 {
            get {
                return ResourceManager.GetString("DialogAlbumMasterShip_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 艦船ID,図鑑番号,艦名,読み,艦種,改装前,改装後,改装Lv,改装弾薬,改装鋼材,改装設計図,耐久初期,耐久最大,耐久結婚,火力初期,火力最大,雷装初期,雷装最大,対空初期,対空最大,装甲初期,装甲最大,対潜初期最小,対潜初期最大,対潜最大,対潜150最小,対潜150最大,回避初期最小,回避初期最大,回避最大,回避150最小,回避150最大,索敵初期最小,索敵初期最大,索敵最大,索敵150最小,索敵150最大,運初期,運最大,速力,射程,レア,スロット数,搭載機数1,搭載機数2,搭載機数3,搭載機数4,搭載機数5,初期装備1,初期装備2,初期装備3,初期装備4,初期装備5,建造時間,解体燃料,解体弾薬,解体鋼材,解体ボーキ,改修火力,改修雷装,改修対空,改修装甲,ドロップ文章,図鑑文章,搭載燃料,搭載弾薬,ボイス,リソース名,バージョン 的本地化字符串。
        /// </summary>
        internal static string DialogAlbumMasterShip_22 {
            get {
                return ResourceManager.GetString("DialogAlbumMasterShip_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 艦船図鑑 CSVの出力に失敗しました。 的本地化字符串。
        /// </summary>
        internal static string DialogAlbumMasterShip_23 {
            get {
                return ResourceManager.GetString("DialogAlbumMasterShip_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 艦船図鑑 CSVの出力に失敗しました。\r\n 的本地化字符串。
        /// </summary>
        internal static string DialogAlbumMasterShip_24 {
            get {
                return ResourceManager.GetString("DialogAlbumMasterShip_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 エラー 的本地化字符串。
        /// </summary>
        internal static string DialogAlbumMasterShip_25 {
            get {
                return ResourceManager.GetString("DialogAlbumMasterShip_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最大値 的本地化字符串。
        /// </summary>
        internal static string DialogAlbumMasterShip_3 {
            get {
                return ResourceManager.GetString("DialogAlbumMasterShip_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基本値 的本地化字符串。
        /// </summary>
        internal static string DialogAlbumMasterShip_4 {
            get {
                return ResourceManager.GetString("DialogAlbumMasterShip_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 装備込 的本地化字符串。
        /// </summary>
        internal static string DialogAlbumMasterShip_5 {
            get {
                return ResourceManager.GetString("DialogAlbumMasterShip_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入渠時の消費:\r\nHP1あたり: 鋼 {0:F2} / 燃 {1:F2}\r\n最大: 鋼 {2} / 燃 {3}\r\n 的本地化字符串。
        /// </summary>
        internal static string DialogAlbumMasterShip_6 {
            get {
                return ResourceManager.GetString("DialogAlbumMasterShip_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 火力 {0}{1}\r\n 的本地化字符串。
        /// </summary>
        internal static string DialogAlbumMasterShip_7 {
            get {
                return ResourceManager.GetString("DialogAlbumMasterShip_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 雷装 {0}{1}\r\n 的本地化字符串。
        /// </summary>
        internal static string DialogAlbumMasterShip_8 {
            get {
                return ResourceManager.GetString("DialogAlbumMasterShip_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 対空 {0}{1}\r\n 的本地化字符串。
        /// </summary>
        internal static string DialogAlbumMasterShip_9 {
            get {
                return ResourceManager.GetString("DialogAlbumMasterShip_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定されたフォルダは存在しません。 的本地化字符串。
        /// </summary>
        internal static string DialogConfiguration_1 {
            get {
                return ResourceManager.GetString("DialogConfiguration_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 艦これに接続してから操作してください。 的本地化字符串。
        /// </summary>
        internal static string DialogConfiguration_2 {
            get {
                return ResourceManager.GetString("DialogConfiguration_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 エラー 的本地化字符串。
        /// </summary>
        internal static string DialogConfiguration_3 {
            get {
                return ResourceManager.GetString("DialogConfiguration_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自動プロキシ設定スクリプトを保存する 的本地化字符串。
        /// </summary>
        internal static string DialogConfiguration_4 {
            get {
                return ResourceManager.GetString("DialogConfiguration_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自動プロキシ設定スクリプトを保存し、設定用URLをクリップボードにコピーしました。\r\n所定の位置に貼り付けてください。 的本地化字符串。
        /// </summary>
        internal static string DialogConfiguration_5 {
            get {
                return ResourceManager.GetString("DialogConfiguration_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 作成完了 的本地化字符串。
        /// </summary>
        internal static string DialogConfiguration_6 {
            get {
                return ResourceManager.GetString("DialogConfiguration_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自動プロキシ設定スクリプトの保存に失敗しました。 的本地化字符串。
        /// </summary>
        internal static string DialogConfiguration_7 {
            get {
                return ResourceManager.GetString("DialogConfiguration_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自動プロキシ設定スクリプトの保存に失敗しました。\r\n 的本地化字符串。
        /// </summary>
        internal static string DialogConfiguration_8 {
            get {
                return ResourceManager.GetString("DialogConfiguration_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 エラー 的本地化字符串。
        /// </summary>
        internal static string DialogConfiguration_9 {
            get {
                return ResourceManager.GetString("DialogConfiguration_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所属艦なし 的本地化字符串。
        /// </summary>
        internal static string FleetData_1 {
            get {
                return ResourceManager.GetString("FleetData_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 開始日時 :  的本地化字符串。
        /// </summary>
        internal static string FleetData_10 {
            get {
                return ResourceManager.GetString("FleetData_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未補給 的本地化字符串。
        /// </summary>
        internal static string FleetData_11 {
            get {
                return ResourceManager.GetString("FleetData_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 燃 : {0}\r\n弾 : {1}\r\nボ : {2} ({3}機) 的本地化字符串。
        /// </summary>
        internal static string FleetData_12 {
            get {
                return ResourceManager.GetString("FleetData_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 疲労  的本地化字符串。
        /// </summary>
        internal static string FleetData_13 {
            get {
                return ResourceManager.GetString("FleetData_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回復目安日時: {0} 的本地化字符串。
        /// </summary>
        internal static string FleetData_14 {
            get {
                return ResourceManager.GetString("FleetData_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 戦意高揚！ 的本地化字符串。
        /// </summary>
        internal static string FleetData_15 {
            get {
                return ResourceManager.GetString("FleetData_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最低cond: {0}\r\nあと {1} 回遠征可能 的本地化字符串。
        /// </summary>
        internal static string FleetData_16 {
            get {
                return ResourceManager.GetString("FleetData_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出撃可能！ 的本地化字符串。
        /// </summary>
        internal static string FleetData_17 {
            get {
                return ResourceManager.GetString("FleetData_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入渠中  的本地化字符串。
        /// </summary>
        internal static string FleetData_18 {
            get {
                return ResourceManager.GetString("FleetData_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 遠征中  的本地化字符串。
        /// </summary>
        internal static string FleetData_19 {
            get {
                return ResourceManager.GetString("FleetData_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入渠中 的本地化字符串。
        /// </summary>
        internal static string FleetData_2 {
            get {
                return ResourceManager.GetString("FleetData_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 疲労  的本地化字符串。
        /// </summary>
        internal static string FleetData_20 {
            get {
                return ResourceManager.GetString("FleetData_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 泊地修理中  的本地化字符串。
        /// </summary>
        internal static string FleetData_21 {
            get {
                return ResourceManager.GetString("FleetData_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完了日時 :  的本地化字符串。
        /// </summary>
        internal static string FleetData_3 {
            get {
                return ResourceManager.GetString("FleetData_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ！！大破進撃中！！ 的本地化字符串。
        /// </summary>
        internal static string FleetData_4 {
            get {
                return ResourceManager.GetString("FleetData_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出撃中 的本地化字符串。
        /// </summary>
        internal static string FleetData_5 {
            get {
                return ResourceManager.GetString("FleetData_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 遠征中 的本地化字符串。
        /// </summary>
        internal static string FleetData_6 {
            get {
                return ResourceManager.GetString("FleetData_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完了日時 :  的本地化字符串。
        /// </summary>
        internal static string FleetData_7 {
            get {
                return ResourceManager.GetString("FleetData_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大破艦あり！ 的本地化字符串。
        /// </summary>
        internal static string FleetData_8 {
            get {
                return ResourceManager.GetString("FleetData_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 泊地修理中 的本地化字符串。
        /// </summary>
        internal static string FleetData_9 {
            get {
                return ResourceManager.GetString("FleetData_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  を起動しています… 的本地化字符串。
        /// </summary>
        internal static string FormMain_1 {
            get {
                return ResourceManager.GetString("FormMain_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ウィンドウ レイアウトを復元しました。 的本地化字符串。
        /// </summary>
        internal static string FormMain_10 {
            get {
                return ResourceManager.GetString("FormMain_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ウィンドウ レイアウト ファイルは存在しません。 的本地化字符串。
        /// </summary>
        internal static string FormMain_11 {
            get {
                return ResourceManager.GetString("FormMain_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 レイアウトが初期化されました。\r\n「表示」メニューからお好みのウィンドウを追加してください。 的本地化字符串。
        /// </summary>
        internal static string FormMain_12 {
            get {
                return ResourceManager.GetString("FormMain_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ウィンドウ レイアウト ファイルが存在しません 的本地化字符串。
        /// </summary>
        internal static string FormMain_13 {
            get {
                return ResourceManager.GetString("FormMain_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ウィンドウ レイアウトの復元に失敗しました。 的本地化字符串。
        /// </summary>
        internal static string FormMain_14 {
            get {
                return ResourceManager.GetString("FormMain_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ウィンドウ レイアウトを保存しました。 的本地化字符串。
        /// </summary>
        internal static string FormMain_15 {
            get {
                return ResourceManager.GetString("FormMain_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ウィンドウ レイアウトの保存に失敗しました。 的本地化字符串。
        /// </summary>
        internal static string FormMain_16 {
            get {
                return ResourceManager.GetString("FormMain_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 セーブしていないレコードが失われる可能性があります。\r\nロードしますか？ 的本地化字符串。
        /// </summary>
        internal static string FormMain_17 {
            get {
                return ResourceManager.GetString("FormMain_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 確認 的本地化字符串。
        /// </summary>
        internal static string FormMain_18 {
            get {
                return ResourceManager.GetString("FormMain_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 APIリストをロード 的本地化字符串。
        /// </summary>
        internal static string FormMain_19 {
            get {
                return ResourceManager.GetString("FormMain_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  API読み込みに失敗しました。 的本地化字符串。
        /// </summary>
        internal static string FormMain_2 {
            get {
                return ResourceManager.GetString("FormMain_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 API読み込みに失敗しました。\r\n 的本地化字符串。
        /// </summary>
        internal static string FormMain_20 {
            get {
                return ResourceManager.GetString("FormMain_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 エラー 的本地化字符串。
        /// </summary>
        internal static string FormMain_21 {
            get {
                return ResourceManager.GetString("FormMain_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 先に通常の api_start2 を読み込んでください。 的本地化字符串。
        /// </summary>
        internal static string FormMain_22 {
            get {
                return ResourceManager.GetString("FormMain_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大変ご迷惑をおかけしております 的本地化字符串。
        /// </summary>
        internal static string FormMain_23 {
            get {
                return ResourceManager.GetString("FormMain_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 旧 api_start2 からレコードを構築 的本地化字符串。
        /// </summary>
        internal static string FormMain_24 {
            get {
                return ResourceManager.GetString("FormMain_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 艦船データが読み込まれていません。 的本地化字符串。
        /// </summary>
        internal static string FormMain_25 {
            get {
                return ResourceManager.GetString("FormMain_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 装備データが読み込まれていません。 的本地化字符串。
        /// </summary>
        internal static string FormMain_26 {
            get {
                return ResourceManager.GetString("FormMain_26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 古いAPIデータを削除します。\r\n本当によろしいですか？ 的本地化字符串。
        /// </summary>
        internal static string FormMain_27 {
            get {
                return ResourceManager.GetString("FormMain_27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 削除が完了しました。\r\n 的本地化字符串。
        /// </summary>
        internal static string FormMain_28 {
            get {
                return ResourceManager.GetString("FormMain_28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  個のファイルを削除しました。 的本地化字符串。
        /// </summary>
        internal static string FormMain_29 {
            get {
                return ResourceManager.GetString("FormMain_29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  起動処理が完了しました。 的本地化字符串。
        /// </summary>
        internal static string FormMain_3 {
            get {
                return ResourceManager.GetString("FormMain_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 削除成功 的本地化字符串。
        /// </summary>
        internal static string FormMain_30 {
            get {
                return ResourceManager.GetString("FormMain_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 削除に失敗しました。\r\n 的本地化字符串。
        /// </summary>
        internal static string FormMain_31 {
            get {
                return ResourceManager.GetString("FormMain_31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 艦船データが読み込まれていません。 的本地化字符串。
        /// </summary>
        internal static string FormMain_32 {
            get {
                return ResourceManager.GetString("FormMain_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通信から保存した艦船リソース名を持つファイル及びフォルダを、艦船名に置換します。\r\n 的本地化字符串。
        /// </summary>
        internal static string FormMain_33 {
            get {
                return ResourceManager.GetString("FormMain_33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 対象は指定されたフォルダ以下のすべてのファイル及びフォルダです。\r\n 的本地化字符串。
        /// </summary>
        internal static string FormMain_34 {
            get {
                return ResourceManager.GetString("FormMain_34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 続行しますか？ 的本地化字符串。
        /// </summary>
        internal static string FormMain_35 {
            get {
                return ResourceManager.GetString("FormMain_35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 艦船リソースをリネーム 的本地化字符串。
        /// </summary>
        internal static string FormMain_36 {
            get {
                return ResourceManager.GetString("FormMain_36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 リネーム処理が完了しました。\r\n{0} 個のアイテムをリネームしました。 的本地化字符串。
        /// </summary>
        internal static string FormMain_37 {
            get {
                return ResourceManager.GetString("FormMain_37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 処理完了 的本地化字符串。
        /// </summary>
        internal static string FormMain_38 {
            get {
                return ResourceManager.GetString("FormMain_38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 艦船リソースのリネームに失敗しました。 的本地化字符串。
        /// </summary>
        internal static string FormMain_39 {
            get {
                return ResourceManager.GetString("FormMain_39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  を終了しますか？ 的本地化字符串。
        /// </summary>
        internal static string FormMain_4 {
            get {
                return ResourceManager.GetString("FormMain_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 艦船リソースのリネームに失敗しました。\r\n 的本地化字符串。
        /// </summary>
        internal static string FormMain_40 {
            get {
                return ResourceManager.GetString("FormMain_40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 外部ブラウザでオンラインヘルプを開きます。\r\nよろしいですか？ 的本地化字符串。
        /// </summary>
        internal static string FormMain_41 {
            get {
                return ResourceManager.GetString("FormMain_41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ヘルプ 的本地化字符串。
        /// </summary>
        internal static string FormMain_42 {
            get {
                return ResourceManager.GetString("FormMain_42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 レイアウト ファイルを開く 的本地化字符串。
        /// </summary>
        internal static string FormMain_43 {
            get {
                return ResourceManager.GetString("FormMain_43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ログインページへ移動します。\r\nよろしいですか？ 的本地化字符串。
        /// </summary>
        internal static string FormMain_44 {
            get {
                return ResourceManager.GetString("FormMain_44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 確認 的本地化字符串。
        /// </summary>
        internal static string FormMain_45 {
            get {
                return ResourceManager.GetString("FormMain_45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移動先の入力 的本地化字符串。
        /// </summary>
        internal static string FormMain_46 {
            get {
                return ResourceManager.GetString("FormMain_46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移動先の URL を入力してください。 的本地化字符串。
        /// </summary>
        internal static string FormMain_47 {
            get {
                return ResourceManager.GetString("FormMain_47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 現在: {0}% 的本地化字符串。
        /// </summary>
        internal static string FormMain_48 {
            get {
                return ResourceManager.GetString("FormMain_48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 API読み込みに失敗しました。\r\n 的本地化字符串。
        /// </summary>
        internal static string FormMain_49 {
            get {
                return ResourceManager.GetString("FormMain_49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 確認 的本地化字符串。
        /// </summary>
        internal static string FormMain_5 {
            get {
                return ResourceManager.GetString("FormMain_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 なし 的本地化字符串。
        /// </summary>
        internal static string FormMain_50 {
            get {
                return ResourceManager.GetString("FormMain_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  を終了しています… 的本地化字符串。
        /// </summary>
        internal static string FormMain_6 {
            get {
                return ResourceManager.GetString("FormMain_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  終了処理が完了しました。 的本地化字符串。
        /// </summary>
        internal static string FormMain_7 {
            get {
                return ResourceManager.GetString("FormMain_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 サブウィンドウ レイアウトの復元に失敗しました。 的本地化字符串。
        /// </summary>
        internal static string FormMain_8 {
            get {
                return ResourceManager.GetString("FormMain_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 サブウィンドウ レイアウトの保存に失敗しました。 的本地化字符串。
        /// </summary>
        internal static string FormMain_9 {
            get {
                return ResourceManager.GetString("FormMain_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 七四式電子観測儀 的本地化字符串。
        /// </summary>
        internal static string SoftwareInformation_1 {
            get {
                return ResourceManager.GetString("SoftwareInformation_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ElectronicObserver 的本地化字符串。
        /// </summary>
        internal static string SoftwareInformation_2 {
            get {
                return ResourceManager.GetString("SoftwareInformation_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一一型改 的本地化字符串。
        /// </summary>
        internal static string SoftwareInformation_3 {
            get {
                return ResourceManager.GetString("SoftwareInformation_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1.1.1 的本地化字符串。
        /// </summary>
        internal static string SoftwareInformation_4 {
            get {
                return ResourceManager.GetString("SoftwareInformation_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新しいバージョンがリリースされています！ : {0}\r\n更新内容 : \r\n{1}\r\nダウンロードページを開きますか？\r\n(キャンセルすると以降表示しません) 的本地化字符串。
        /// </summary>
        internal static string SoftwareInformation_5 {
            get {
                return ResourceManager.GetString("SoftwareInformation_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 アップデート情報 的本地化字符串。
        /// </summary>
        internal static string SoftwareInformation_6 {
            get {
                return ResourceManager.GetString("SoftwareInformation_6", resourceCulture);
            }
        }
    }
}
